version: "3.8"

# services:
#   app:
#     container_name: app-prod
#     image: app-prod
#     build:
#       context: .
#       dockerfile: Dockerfile.prod
#       target: production
#     stdin_open: true


services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.prod
    stdin_open: true
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./build:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf

